# Generated by Django 3.2.6 on 2021-09-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_like_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
    ]
