# Generated by Django 3.2.6 on 2021-09-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
