# Generated by Django 3.2.6 on 2021-09-11 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_follow_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed',
        ),
        migrations.AddField(
            model_name='follow',
            name='followed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
