# Generated by Django 3.2.6 on 2021-09-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210911_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='state',
        ),
    ]
