# Generated by Django 3.2.6 on 2021-09-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_follow_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='editado',
            field=models.BooleanField(default=False),
        ),
    ]
