# Generated by Django 3.2.6 on 2021-08-29 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='response',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='auction_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
