# Generated by Django 3.2.6 on 2021-08-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='list',
            field=models.ManyToManyField(to='auctions.Auction'),
        ),
    ]
